// This file is generated by pnpm build:icons

export type IconName =
  | "chevron-left"
  | "chevron-right"
  | "eye-off"
  | "eye"
  | "home"
  | "log-out"
  | "mail"
  | "monitor"
  | "moon"
  | "search"
  | "sun"
  | "user-plus"
  | "user"
  | "users";
